version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: h2r
      MYSQL_ROOT_PASSWORD: h2r@123456
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    restart: always
    environment:
      PMA_HOST: mysql

volumes:
  mysql-volume:
