services:
  h2r:
    image: 381491905102.dkr.ecr.us-east-1.amazonaws.com/bohmid/h2r:v1
    container_name: h2r
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - h2r-api
    networks:
      - prometheus

  h2r-api:
    image: 381491905102.dkr.ecr.us-east-1.amazonaws.com/bohmid/h2r-backend:v1
    container_name: h2r-api
    ports:
      - "5001:3000"
    restart: always
    depends_on:
      - h2r-db
    networks:
      - prometheus
    environment:
      DB_HOST: h2r-db
      DB_USER: root
      DB_PASSWORD: h2r@123456
      DB_NAME: h2r
      DB_PORT: 3306
      PORT: 3000
      JWT_SECRET: 9bd113df7c98d986e606966f910c9e2c80a28027320ff07d2a8a0897a2233e4e

  h2r-db:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    volumes:
      - h2r-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: h2r
      MYSQL_ROOT_PASSWORD: h2r@123456
    ports:
      - 3306:3306
    networks:
      - prometheus

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    restart: always
    environment:
      PMA_HOST: h2r-db
    depends_on:
      - h2r-db
    networks:
      - prometheus

networks:
  prometheus:
    name: prometheus
    external: true

volumes:
  h2r-db-volume:
